---

- name: nomad | check if file is downloaded
  become: false
  stat:
    path: "{{ base_dir['downloads'] }}/{{ package_name_nomad }}.zip"
  register: package_status_nomad

- block:

  - name: nomad | download package
    become: false
    get_url:
      url: "{{ package_url_nomad }}"
      dest: "{{ base_dir['downloads'] }}"
      checksum: "sha256:{{ checksum_url_nomad }}"
      validate_certs: false
    register: download_status_nomad

  when: not package_status_nomad['stat']['exists']
