#
# Configures the nomad server
#
---

- name: nomad | start and enable unit
  become: true
  notify:
  - reload_systemd_daemon
  systemd:
    name: nomad
    masked: no
    enabled: yes
    state: started
