---

- name: nomad | extract binary
  become: true
  unarchive:
    src: "{{ os_dir_temp }}/{{ package_name_nomad }}.zip"
    dest: "{{ os_dir_packages }}/nomad/{{ nomad_version }}"
    remote_src: yes

- name: nomad | symlink binary
  become: true
  notify:
  - restart_unit_nomad
  file:
    src: "{{ os_dir_packages }}/nomad/{{ nomad_version }}/nomad"
    path: "{{ os_dir_binaries }}/nomad"
    state: link
