---
# tasks file for roles/nomad

- name: only run if os is supported
  block:

  - include_vars: coreos.yml
    when: ansible_service_mgr == "systemd"

  - include: nomad-download.yml
    tags: download

  - include: nomad-install.yml
    tags: install

  - block:

    - include: nomad-cfg_user.yml
      tags: optional

    - include: nomad-cfg_systemd.yml
      tags: optional

    - include: nomad-cfg_server.yml
      tags: optional

    when: nomad['server'] or nomad['client']

  when: ansible_service_mgr == "systemd"
