#
# Installs the nomad binary
# - Binary: /<package directory>/nomad/<version>/nomad
# - Symlink: /<binary directory>/nomad
#
---

- name: nomad | create installation folders
  become: true
  file:
    path: "{{ base_dir['packages'] }}/{{ bin_name['nomad'] }}/{{ nomad['version'] }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: nomad | extract binary
  become: true
  unarchive:
    src: "{{ base_dir['downloads'] }}/{{ package_name_nomad }}.zip"
    dest: "{{ base_dir['packages'] }}/{{ bin_name['nomad'] }}/{{ nomad['version'] }}"
    remote_src: yes

- name: nomad | symlink binary
  become: true
  file:
    src: "{{ base_dir['packages'] }}/{{ bin_name['nomad'] }}/{{ nomad['version'] }}/{{ bin_name['nomad'] }}"
    path: "{{ base_dir['binaries'] }}/{{ bin_name['nomad'] }}"
    state: link
