---

- name: nomad | generate sever configurationfiles
  become: true
  notify:
  - reload_systemd_daemon
  - restart_unit_nomad
  template:
    dest: "{{ base_dir['configs'] }}/{{ bin_name['nomad'] }}.d/{{ item }}"
    src: "{{ bin_name['nomad'] }}/{{ item }}.j2"
    owner: "{{ bin_name['nomad'] }}"
    group: "{{ bin_name['nomad'] }}"
    mode: 0640
  loop:
  - 50-autopilot.hcl
  - 50-consul.hcl
  - 50-vault.hcl
  - 50-acl.hcl
