#
# Downloads the nomad binary
#
---

- name: nomad | check if file is downloaded
  become: false
  stat:
    path: "{{ base_dir['downloads'] }}/{{ package_name_nomad }}.zip"
  register: package_status_nomad

- name: nomad | download package
  block:

  - name: nomad | get package checksum
    run_once: true
    become: false
    local_action: shell curl -s "{{ checksum_url_nomad }}" | grep -i "{{ package_name_nomad }}.zip" | awk '{print $1}'
    args:
      warn: false
    register: sha256_nomad

  - name: nomad | download package
    become: false
    get_url:
      url: "{{ package_url_nomad }}"
      dest: "{{ base_dir['downloads'] }}"
      checksum: "sha256:{{ sha256_nomad['stdout'] }}"
      validate_certs: false
    register: download_status_nomad

  when: not package_status_nomad['stat']['exists']
